services:
  app:
    container_name: caputalsight-api
    tty: true
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/app
    networks:
      - capital_network
networks:
  capital_network:
    driver: bridge
